<?php

namespace Tests\Feature;

use App\Http\Controllers\Api\v1\AuthController;
use App\Models\Panel;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class AuthTest extends TestCase
{
    public $panel;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->panel = Panel::factory()->create(['password' => 1234]);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_can_panel_auth()
    {
        $this->postJson(action([AuthController::class]),[
           'username' => $this->panel->username,
           'password' => 1234
        ])->assertStatus(200);
    }
}
